name: Build MacOS App and Publish Release

on:
  push:
    tags:
      - 'v*'  # Trigger workflow on version tags like v1.0, v1.1, etc.

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        python-version: ['3.9', '3.10']  # Add the versions of Python you want to test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install py2app

      - name: Build with py2app
        run: |
          python setup.py py2app

      - name: Compress app into zip
        run: zip -r MyApp-${{ github.ref }}.zip dist/*.app

      - name: Install GitHub CLI
        run: |
          brew install gh

      - name: Create Release and Upload Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
        run: |
          gh release create ${{ github.ref }} MyApp-${{ github.ref }}.zip --title "Release ${{ github.ref }}" --notes "Automatically generated release"
