name: Build MacOS App and Publish Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'  # Trigger workflow on version tags like v1.0, v1.1, etc.

jobs:
  build:
    strategy:
      matrix:
        python-version: ['3.9']  # Add the versions of Python you want to test
        os: [macos-11, macos-12]  # macos-11 for Intel, macos-12 for M1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install py2app

      - name: Extract tag name
        id: extract_tag
        run: echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build with py2app
        run: |
          python setup.py py2app
          echo "Build completed"
          ls -lh dist/
          ls -lh dist/*.app

      - name: Compress app into zip
        run: |
          zip -r MyApp-${{ env.TAG_NAME }}-${{ matrix.os }}.zip dist/*.app
          ls -lh MyApp-${{ env.TAG_NAME }}-${{ matrix.os }}.zip

      - name: Install GitHub CLI
        if: runner.os == 'macOS-11'
        run: |
          brew install gh

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
        run: |
          gh release create ${{ env.TAG_NAME }} --title "Release ${{ env.TAG_NAME }}" --notes "Automatically generated release"

      - name: Upload Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
        run: |
          gh release upload ${{ env.TAG_NAME }} MyApp-${{ env.TAG_NAME }}-${{ matrix.os }}.zip